In [2]:
import numpy as np

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array = np.full(5, 2.0)
array

array([2., 2., 2., 2., 2.])

In [5]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0, 3, 11)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. ])

In [7]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Randomly generated arrays
np.random.seed(3)
np.random.rand(5, 2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

In [9]:
np.random.seed(3)
np.random.randn(5, 2)

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898],
       [-0.08274148, -0.62700068],
       [-0.04381817, -0.47721803]])

In [10]:
np.random.seed(3)
np.random.randint(low=0, high=100, size=(5, 2))

array([[24,  3],
       [56, 72],
       [ 0, 21],
       [19, 74],
       [41, 10]])

In [34]:
# Element-wise operations
a = np.arange(6)
b = 10 + (a*2) / 100

In [35]:
c = a + b
c

array([10.  , 11.02, 12.04, 13.06, 14.08, 15.1 ])

In [36]:
b >= 15

array([False, False, False, False, False, False])

In [37]:
a > b

array([False, False, False, False, False, False])

In [38]:
a[a > b]

array([], dtype=int32)

In [ ]:
c = a + b
c

array([10.  , 11.02, 12.04, 13.06, 14.08, 15.1 ])

In [41]:
np.random.seed(5)
pred = np.random.rand(2).round(4)
pred

array([0.222 , 0.8707])

In [47]:
a
b.std()

0.034156502553198714